[package]
name = "rmsc-lsp"
version = "0.1.0"
description = "An LSP for AoE2:DE's flavour of RMS"
license.workspace = true
edition.workspace = true
authors.workspace = true

[build-dependencies]
chrono = "0.4.38"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
dashmap = { workspace = true }
dunce = { workspace = true }
env_logger = "0.11.7"
ropey = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "io-std"]}
tower-lsp = { workspace = true }
rmsc-core = { path = "../rmsc-core", features = ["lsp"] }

[[bin]]
name = "rms-check-lsp"
path = "src/main.rs"
bench = false
